[project]
name = "git-remote-s3"
version = "0.3.2"
description = "A git remote helper for Amazon S3"
authors = [{ email = "Massimiliano Angelino <angmas@amazon.com>" }]
requires-python = ">= 3.10"
readme = "README.md"
license = "Apache-2.0"
classifiers = [
    "Topic :: Software Development :: Version Control",
    "Topic :: Software Development :: Version Control :: Git",
]
dependencies = [
    "boto3 (>=1.42.24,<2.0.0)",
    "botocore (>=1.42.24,<2.0.0)",
    "urllib3 (>=2.6.3,<3.0.0)",
]
repository = "https://github.com/awslabs/git-remote-s3"

[project.optional-dependencies]
gcs = ["google-cloud-storage (>=2.0.0,<3.0.0)"]

[project.scripts]
git-remote-s3 = "git_remote_s3.remote:main"
"git-remote-s3+zip" = "git_remote_s3.remote:main"
git-lfs-s3 = "git_remote_s3.lfs:main"
git-s3 = "git_remote_s3.manage:main"
git-remote-gcs = "git_remote_s3.remote:main"
git-remote-gs = "git_remote_s3.remote:main"

[dependency-groups]
dev = [
    "flake8>=7.1.1,<8",
    "flake8-bugbear>=24.4.26,<25",
    "mypy>=1.11.1,<2",
    "pytest>=8.3.2,<9",
    "mock>=5.1.0,<6",
    "black>=26.3.1,<27",
    "coverage>=7.6.1,<8",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.10.8,<0.11.0"]
build-backend = "uv_build"
